local request = http.get("https://github.com/Keyditor/newspkm/raw/main/news.lua")
news = request.readAll()
file = fs.open("news2.lua","w")
file.write(news)
file.close()
request = http.get("https://github.com/Keyditor/newspkm/raw/main/salt.lua")
news = request.readAll()
file = fs.open("salt.lua","w")
file.write(news)
file.close()
request = http.get("https://github.com/Keyditor/newspkm/raw/main/models.lua")
news = request.readAll()
file = fs.open("models.lua","w")
file.write(news)
file.close()
request = http.get("https://github.com/Keyditor/newspkm/raw/main/update.lua")
news = request.readAll()
file = fs.open("update.lua","w")
file.write(news)
file.close()
shell.run("news2.lua")